/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UiOptions {
  /**
   * Name of the UI library
   */
  name: string;
  /**
   * Whether the library should be shared across all domains.
   */
  shared?: boolean;
  /**
   * Domain name, if the library belongs to a certain domain.
   */
  domain?: string;
  /**
   * Apply the "ui-" prefix?
   */
  prefix?: boolean;
  /**
   * Additional custom prefix for selectors and class names
   */
  additionalPrefix?: string;
  /**
   * Subpath of the library beneath the domain or shared folder.
   */
  directory?: string;
  /**
   * For publishable libs: Official package name used in import statements
   */
  importPath?: string;
  /**
   * A type to determine if and how to build the library.
   */
  type?: "internal" | "buildable" | "publishable";
  /**
   * Use standalone components?
   */
  standalone?: boolean;
  /**
   * Create a flat library structure?
   */
  flat?: boolean;
  /**
   * Don't include the directory in the name of the module or standalone component entry of the library.
   */
  simpleName?: boolean;
  /**
   * The file extension or preprocessor to use for style files
   */
  style?: "css" | "scss" | "sass" | "less" | "none";
  [k: string]: unknown;
}
