/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FeatureOptions {
  /**
   * Library name
   */
  name: string;
  /**
   * Domain name
   */
  domain: string;
  /**
   * app name
   */
  app?: string;
  /**
   * Is this feature module lazy loaded?
   */
  lazy?: boolean;
  /**
   * Optional entity to create for this feature
   */
  entity?: string;
  [k: string]: any;
}
