# DO NOT CHANGE THIS FILE!
# This file is managed and synced from https://github.com/adup-tech/devops_git-workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    tags-ignore:
      - '**'
    paths-ignore:
      - '.github/**'
      - 'README.md'  # a change in the README file on its own shouldn't cause a version bump

permissions:
  contents: write
  pull-requests: write

name: Create Release

jobs:
  release-pr:
    name: Create Release Pull Request
    uses: adup-tech/nx-ddd-plugin/.github/workflows/_create_release_pr.yaml@main
    secrets: inherit
    with:
      release-type: node
      default-branch: ${{ github.head_ref || github.ref_name }} # use branch name if not a PR
